# Generated by Django 3.2 on 2021-04-08 21:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('birth_date', models.DateField(verbose_name='Birthday')),
                ('birth_place', models.CharField(max_length=200, verbose_name='Birthplace')),
                ('biography', models.TextField(max_length=5000, verbose_name='Bio')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200, unique=True, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('production_company', models.CharField(max_length=200, verbose_name='Production Company')),
                ('distribution_company', models.CharField(max_length=200, verbose_name='Distributed By')),
                ('date_released', models.DateField(verbose_name='Release Date')),
                ('movie_rated', models.CharField(max_length=5, verbose_name='Rated')),
                ('movie_length', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(51420)], verbose_name='Running Time')),
                ('plot', models.TextField(max_length=5000, verbose_name='Plot')),
                ('crew', models.ManyToManyField(related_name='movies', to='movies.Crew', verbose_name='Cast and Crew')),
                ('genre', models.ManyToManyField(related_name='movies', to='movies.Genre', verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Role')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='movies.crew')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Viewer Rating')),
                ('title', models.CharField(max_length=60)),
                ('comment', models.TextField(max_length=300)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
