# Generated by Django 3.2 on 2021-04-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castandcrew',
            options={'verbose_name': 'Cast and Crew', 'verbose_name_plural': 'Cast and Crew'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name_plural': 'People'},
        ),
    ]
