# Generated by Django 3.2 on 2021-04-12 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='biography',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='birth_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Birthplace'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Crew', verbose_name='Cast and Crew'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_released',
            field=models.DateField(blank=True, verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='distribution_company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Distributed By'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_length',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(51420)], verbose_name='Running Time'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_rated',
            field=models.CharField(blank=True, max_length=5, verbose_name='Rated'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Plot'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Production Company'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
