# Generated by Django 3.2 on 2021-04-12 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210412_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='movies.Crew', verbose_name='Cast and Crew'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_released',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='movies.Genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_length',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(51420)], verbose_name='Running Time'),
        ),
    ]
