# Generated by Django 3.2 on 2021-04-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210412_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castandcrew',
            old_name='name',
            new_name='person',
        ),
    ]
