# Generated by Django 3.2 on 2021-04-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210412_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Crew', verbose_name='Cast and Crew'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Genre', verbose_name='Genre'),
        ),
    ]
